### **Installation des packages (librairies) :**

In [ ]:
! pip install -r /workspaces/Heatmap-of-correlation-between-BRVM-equities/requirements.txt

In [4]:
import brvmfinance as bf           #On importe brvmfinance pour accéder aux données financières de la BRVM
import matplotlib.pyplot as plt    #On importe matplotlib.pyplot pour visualiser les données financières de la BRVM
import pandas as pd                #On importe pandas pour gerer les data-frames des données financières
import seaborn as sns              #On importe seaborn pour visualiser nos données de manière plus esthétique

### 1) Téléchargement :

Pour télécharger nos donné on se servira du package python **brvmfinance** avec ses fonctions :

```
Ticker(str) 
```
```
history(int) 
```

In [5]:
# Nous commençon par déclarer notre variabl tick comme notre ticker
tick = "BOAC"

# On crée l'objet ticker
tickers  = bf.Ticker(tick)

# On charge notre l'historique de notre ticker lors des n derniers jours
n = 100
df = tickers.history(length = n)

# On affiche le data frame
df.head(3)

            Open  High   Low  Close  Volume
Date
2026-05-22  8850  8870  8850   8870    4515
2026-05-25  8850  8870  8850   8870    4515
2026-05-26  8850  8850  8825   8825    4991

### 1) Fonction de chargement pour plusieurs tickers :

Jusque là nous avons téléchargé l'historique d'une seul action. Danc le cas ou nous voudrions l'historique d'une ou **plusieurs** actions, nous allons créer la fonction :

```
download_tickers(ticker(s) : list[str], time : int, OHLC : str = "close") -> pd.DataFrame
```

In [9]:
def download_tickers(tickers : list[str], time : int, OHLC : str = "Close") -> pd.DataFrame :

    # On crée une liste vide pour stocker les dataframes de chaque ticker
  names = []

    # La boucle for télécharge le dataframe de chaque ticker et l'ajoute à la liste names avec le nom du ticker comme nom de colonne 
  for ticker in tickers :

      tick = bf.Ticker(ticker)
      dfi = tick.history(length = time)[OHLC]
      dfi.columns = [ticker]

      names.append(dfi)

    # On concatène les dataframes de chaque ticker en un seul dataframe avec les noms des tickers comme noms de colonnes
  df = pd.concat(names, axis=1)
  df.columns = tickers

    # La sortie sera un dataframe composé formé à partir de l'historique de chaque ticker
  return df

#### Test : download_tickers()

In [8]:
df = download_tickers(["BOAC", "BOAN"], 100)

df.head(3)

            BOAC  BOAN
Date
2026-05-22  8870  3730
2026-05-25  8870  3730
2026-05-26  8825  3740